In [2]:
import torch

In [3]:
x = torch.rand(2)
print(x)

x = torch.rand(2, 2)
print(x)

x = torch.rand(2, 2, 2, 2)
print(x)

tensor([0.4419, 0.2791])
tensor([[0.8929, 0.9857],
        [0.8392, 0.5835]])
tensor([[[[0.4655, 0.9292],
          [0.7894, 0.3005]],

         [[0.6328, 0.7925],
          [0.1089, 0.0900]]],


        [[[0.2844, 0.6230],
          [0.6881, 0.6846]],

         [[0.7890, 0.6661],
          [0.6992, 0.3096]]]])


In [4]:
x = torch.zeros(2)
print(x)

x = torch.ones(2, 2)
print(x)

x = torch.tensor([5.5, 3])
print(x)

x = torch.tensor([[[5.5, 3], [4, 6]], [[1, 2], [3, 4]]])
print(x)

tensor([0., 0.])
tensor([[1., 1.],
        [1., 1.]])
tensor([5.5000, 3.0000])
tensor([[[5.5000, 3.0000],
         [4.0000, 6.0000]],

        [[1.0000, 2.0000],
         [3.0000, 4.0000]]])


In [5]:
import numpy as np

In [6]:
x = torch.ones(2, 3)
y = torch.ones(2, 3)
res = x+y
print(res)

tensor([[2., 2., 2.],
        [2., 2., 2.]])


In [7]:
x = torch.rand(2, 3)
x_t = x.t()
res = torch.mm(x, x_t)
print(res)

tensor([[1.2000, 0.6453],
        [0.6453, 0.9103]])


In [8]:
x = torch.ones(3, 3)
print(x)

y = x + 10
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[11., 11., 11.],
        [11., 11., 11.],
        [11., 11., 11.]])


In [12]:
x = torch.ones(3, 3, requires_grad = True)
print(x)

y = x * 10
print(y)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)
tensor([[10., 10., 10.],
        [10., 10., 10.],
        [10., 10., 10.]], grad_fn=<MulBackward0>)


In [20]:
x = torch.randn(3, 3)
x = ((x*3) / (x-1))
print(x.requires_grad)

x.requires_grad_(True)
print(x.requires_grad)

y=(x*x).sum()
print(y)
print(y.grad_fn)

False
True
tensor(12506.4580, grad_fn=<SumBackward0>)


In [27]:
x = torch.randn(3, 3, requires_grad = True)
print(x)
y = ((x*3) / (x-1))
print(y)

z = (x*x).sum()
print(x*x)

print(z)
print(z.grad_fn)

z.backward()
print(x.grad)

tensor([[-0.3288,  0.4428,  0.4558],
        [-0.8701, -0.0756,  1.1462],
        [ 0.3282, -2.1403,  0.2339]], requires_grad=True)
tensor([[ 0.7423, -2.3837, -2.5129],
        [ 1.3958,  0.2110, 23.5237],
        [-1.4655,  2.0447, -0.9158]], grad_fn=<DivBackward0>)
tensor([[0.1081, 0.1960, 0.2078],
        [0.7571, 0.0057, 1.3137],
        [0.1077, 4.5810, 0.0547]], grad_fn=<MulBackward0>)
tensor(7.3318, grad_fn=<SumBackward0>)
None
tensor([[-0.6576,  0.8855,  0.9116],
        [-1.7402, -0.1513,  2.2923],
        [ 0.6564, -4.2806,  0.4678]])
