# 1. Linear Equations

## 1.1. Solving Linear Equations

In [1]:
import numpy as np

In [3]:
A = np.array([[4, -5], [-2, 3]])
A

array([[ 4, -5],
       [-2,  3]])

In [7]:
b = np.array([[-13], [9]])
b

array([[-13],
       [  9]])

In [9]:
# method 1
A_inv = np.linalg.inv(A)
x = A_inv.dot(b)
x

array([[3.],
       [5.]])

In [10]:
# method 2
x = A_inv @ b
x

array([[3.],
       [5.]])

In [13]:
# method 3
A = np.asmatrix(A)
b = np.asmatrix(b)
x = A.I * b
x

matrix([[3.],
        [5.]])

## 1.4. Vector-Vector Products

In [16]:
x = np.array([[1],
              [1]])

y = np.array([[2],
              [3]])

x.T @ y

array([[5]])

# 2. Norms

In [19]:
x = np.array([[4], 
              [3]])

np.linalg.norm(x, 2)

5.0

In [20]:
np.linalg.norm(x, 1)

7.0

# 3. System of Linear Equations

# 4. Optimization Point of View

In [21]:
A = np.matrix([[1,0],
               [0,1],
               [0,0]])
B = np.matrix([[1],
               [1],
               [1]])

X = (A.T * A).I * A.T * B
X

matrix([[1.],
        [1.]])

In [23]:
Bstar = A * X
Bstar

matrix([[1.],
        [1.],
        [0.]])