In [1]:
import numpy as np
import pandas as pd
import pickle

## 실습 내용

## 1. Jupyter notebook basic
자주 사용 하는 단축키들


##  주석 1

In [2]:
# esc: command mode
# entder: edit mode

# Command mode
# a: 위에 셀 추가
# b: 아래 셀 추가
# o: 결과창 숨기기

In [3]:
# edit mode
# ctrl + shift + - : 현재 기준으로 셀 나누기

## 2. Pandas

### 2.1 파일 불러들이기

In [4]:
#jupyter notebook 상에서 library 설치
!pip install xlrd

In [5]:
df = pd.read_csv('./Dataset/dataset_city.csv')

In [6]:
type(df) #EQ의 자료형 확인

pandas.core.frame.DataFrame

In [7]:
# ctrl + enter: 현재 셀만 실행
# alt + enter : 현재 셀 실행 후 아래에 새로운 셀 추가
# shift + enter : 현재 셀 실행 후 아래 셀로 이동

In [8]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

### 2.2 pandas dataframe 살펴보기

In [9]:
?df.head # df.head에 대한 설명

Object `df.head # df.head에 대한 설명` not found.


In [10]:
df.head(5) #처음 5개 row 살펴보기

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   
2  Ahmedabad  2015-01-01 3:00   NaN   NaN  0.08  19.32  11.08   NaN  0.08   
3  Ahmedabad  2015-01-01 4:00   NaN   NaN  0.30  16.45   9.20   NaN  0.30   
4  Ahmedabad  2015-01-01 5:00   NaN   NaN  0.12  14.90   7.85   NaN  0.12   

    col10   col11  col12  col13  col14  col15 col16  
0  122.07     NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90     NaN    0.0    0.0    0.0    NaN   NaN  
2   52.83     NaN    0.0    0.0    0.0    NaN   NaN  
3   39.53  153.58    0.0    0.0    0.0    NaN   NaN  
4   32.63     NaN    0.0    0.0    0.0    NaN   NaN

In [11]:
df['col2']

0          2015-01-01 1:00
1          2015-01-01 2:00
2          2015-01-01 3:00
3          2015-01-01 4:00
4          2015-01-01 5:00
                ...       
670825    2020-06-30 20:00
670826    2020-06-30 21:00
670827    2020-06-30 22:00
670828    2020-06-30 23:00
670829     2020-07-01 0:00
Name: col2, Length: 670830, dtype: object

In [12]:
# loc(location): label을 이용하여 접근
df.loc[0:2,'col3':'col6']

col3  col4  col5   col6
0   NaN   NaN  1.00  40.01
1   NaN   NaN  0.02  27.75
2   NaN   NaN  0.08  19.32

In [13]:
df.loc[:5,:'col4']

col1             col2  col3  col4
0  Ahmedabad  2015-01-01 1:00   NaN   NaN
1  Ahmedabad  2015-01-01 2:00   NaN   NaN
2  Ahmedabad  2015-01-01 3:00   NaN   NaN
3  Ahmedabad  2015-01-01 4:00   NaN   NaN
4  Ahmedabad  2015-01-01 5:00   NaN   NaN
5  Ahmedabad  2015-01-01 6:00   NaN   NaN

In [14]:
df.loc[:,'col2':'col3']

col2   col3
0        2015-01-01 1:00    NaN
1        2015-01-01 2:00    NaN
2        2015-01-01 3:00    NaN
3        2015-01-01 4:00    NaN
4        2015-01-01 5:00    NaN
...                  ...    ...
670825  2020-06-30 20:00   9.50
670826  2020-06-30 21:00  17.25
670827  2020-06-30 22:00  36.00
670828  2020-06-30 23:00  15.75
670829   2020-07-01 0:00  15.00

[670830 rows x 2 columns]

In [15]:
# iloc(index locaiton): 위치 정수를 통한 접근
df.iloc[:2,:]

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   

    col10  col11  col12  col13  col14  col15 col16  
0  122.07    NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90    NaN    0.0    0.0    0.0    NaN   NaN

In [16]:
df.iloc[2:4,4:1:-1]

col5  col4  col3
2  0.08   NaN   NaN
3  0.30   NaN   NaN

In [17]:
df.head()

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   
2  Ahmedabad  2015-01-01 3:00   NaN   NaN  0.08  19.32  11.08   NaN  0.08   
3  Ahmedabad  2015-01-01 4:00   NaN   NaN  0.30  16.45   9.20   NaN  0.30   
4  Ahmedabad  2015-01-01 5:00   NaN   NaN  0.12  14.90   7.85   NaN  0.12   

    col10   col11  col12  col13  col14  col15 col16  
0  122.07     NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90     NaN    0.0    0.0    0.0    NaN   NaN  
2   52.83     NaN    0.0    0.0    0.0    NaN   NaN  
3   39.53  153.58    0.0    0.0    0.0    NaN   NaN  
4   32.63     NaN    0.0    0.0    0.0    NaN   NaN

In [18]:
#  변수 형태 살펴보기
df.dtypes

col1      object
col2      object
col3     float64
col4     float64
col5     float64
col6     float64
col7     float64
col8     float64
col9     float64
col10    float64
col11    float64
col12    float64
col13    float64
col14    float64
col15    float64
col16     object
dtype: object

In [19]:
# 요약
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670830 entries, 0 to 670829
Data columns (total 16 columns):
 #   Column  Non-Null Count   Dtype  
---  ------  --------------   -----  
 0   col1    670830 non-null  object 
 1   col2    670830 non-null  object 
 2   col3    530858 non-null  float64
 3   col4    380931 non-null  float64
 4   col5    558625 non-null  float64
 5   col6    557935 non-null  float64
 6   col7    551494 non-null  float64
 7   col8    407200 non-null  float64
 8   col9    586398 non-null  float64
 9   col10   543891 non-null  float64
 10  col11   547372 non-null  float64
 11  col12   515584 non-null  float64
 12  col13   460298 non-null  float64
 13  col14   243501 non-null  float64
 14  col15   545725 non-null  float64
 15  col16   545725 non-null  object 
dtypes: float64(13), object(3)
memory usage: 81.9+ MB


In [20]:
df.describe()

col3           col4           col5           col6  \
count  530858.000000  380931.000000  558625.000000  557935.000000   
mean       70.067364     124.037024      17.813423      29.589279   
std        76.084568     105.663468      32.702488      29.593462   
min         0.010000       0.010000       0.010000       0.010000   
25%        27.750000      56.610000       3.900000      11.110000   
50%        48.500000      94.890000       8.080000      21.000000   
75%        82.250000     153.100000      16.450000      37.220000   
max       999.990000    1000.000000     499.990000     499.510000   

                col7           col8           col9          col10  \
count  551494.000000  407200.000000  586398.000000  543891.000000   
mean       32.957969      24.268378       2.265773      14.312244   
std        40.536889      29.545867      11.286639      19.788800   
min         0.000000       0.010000       0.000000       0.010000   
25%        10.720000       8.310000       0.420000       4.800000   
50%        21.240000      15.900000       0.810000       8.400000   
75%        37.930000      29.930000       1.380000      15.100000   
max       498.610000     499.970000     498.570000     199.960000   

               col11          col12          col13          col14  \
count  547372.000000  515584.000000  460298.000000  243501.000000   
mean       34.807954       3.127310       8.923422       3.146776   
std        29.930581      16.525254      21.948098       7.944772   
min         0.010000       0.000000       0.000000       0.000000   
25%        13.280000       0.080000       0.470000       0.090000   
50%        26.180000       0.920000       2.770000       0.780000   
75%        47.680000       2.830000       8.750000       3.120000   
max       497.620000     498.070000     499.400000     499.990000   

               col15  
count  545725.000000  
mean      171.587336  
std       165.261902  
min         9.000000  
25%        81.000000  
50%       120.000000  
75%       217.000000  
max      3133.000000

In [21]:
df['col3'].mean()

70.06736366410706

In [22]:
df['col3'].std()

76.08456799269662

### 2.3 특정 조건에 행이나 열 선택하기

In [23]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [24]:
# 열 'col5'가 1 이상인 것들만 선택하기
idx1 = df['col5']>=1
print(idx1)

0          True
1         False
2         False
3         False
4         False
          ...  
670825     True
670826     True
670827     True
670828     True
670829    False
Name: col5, Length: 670830, dtype: bool


In [25]:
df[idx1]

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
7           Ahmedabad   2015-01-01 8:00    NaN    NaN  1.03  16.66  16.48   
8           Ahmedabad   2015-01-01 9:00    NaN    NaN  1.47  16.25  18.02   
9           Ahmedabad  2015-01-01 10:00    NaN    NaN  2.05  13.78  16.08   
10          Ahmedabad  2015-01-01 11:00    NaN    NaN  2.27  13.87  16.73   
...               ...               ...    ...    ...   ...    ...    ...   
670823  Visakhapatnam  2020-06-30 18:00   6.50  24.75  2.25  23.38  13.68   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   

         col8  col9   col10   col11  col12  col13  col14  col15         col16  
0         NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
7         NaN  1.03   20.92  177.21    0.0    0.0    0.0    NaN           NaN  
8         NaN  1.47   16.45  122.08    0.0    0.0    0.0    NaN           NaN  
9         NaN  2.05   15.14     NaN    0.0    0.0    0.0    NaN           NaN  
10        NaN  2.27   14.12   99.17    0.0    0.0    0.0    NaN           NaN  
...       ...   ...     ...     ...    ...    ...    ...    ...           ...  
670823  10.60  0.66    5.80   33.55    NaN    NaN    NaN   51.0  Satisfactory  
670825   4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826   3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827   3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828   3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  

[538713 rows x 16 columns]

In [26]:
idx2 = (df['col5']>=1 ) & (df['col9']<=0.5)
print(idx2)
df[idx2]

0         False
1         False
2         False
3         False
4         False
          ...  
670825    False
670826    False
670827    False
670828     True
670829    False
Length: 670830, dtype: bool


col1              col2   col3    col4   col5   col6   col7  \
46224       Ahmedabad   2020-04-10 1:00  68.81  136.03   5.23  39.01  22.93   
46225       Ahmedabad   2020-04-10 2:00  60.53  124.78   3.83  22.58  13.87   
46226       Ahmedabad   2020-04-10 3:00  43.08  105.17   3.94  17.66  11.55   
46227       Ahmedabad   2020-04-10 4:00  35.20   90.28   5.67  24.95  16.41   
46231       Ahmedabad   2020-04-10 8:00  23.55   63.03   8.29  18.92  15.42   
...               ...               ...    ...     ...    ...    ...    ...   
670810  Visakhapatnam   2020-06-30 5:00  13.50   44.75   6.60  35.15  24.05   
670811  Visakhapatnam   2020-06-30 6:00  15.00   50.00  15.45  36.88  32.20   
670819  Visakhapatnam  2020-06-30 14:00  10.75   36.75   1.10  17.75  10.28   
670821  Visakhapatnam  2020-06-30 16:00  14.00   29.50   1.77  20.70  12.45   
670828  Visakhapatnam  2020-06-30 23:00  15.75   63.00   1.02  28.90  16.00   

        col8  col9  col10  col11  col12   col13  col14  col15         col16  
46224    NaN  0.27  44.82  11.11  22.46  105.65   8.73  127.0      Moderate  
46225    NaN  0.19  67.26   9.76  10.52  100.23   5.00  127.0      Moderate  
46226    NaN  0.18  42.30   9.79   5.09   36.42   2.94  127.0      Moderate  
46227    NaN  0.42  57.69   9.99   3.87   22.38   1.90  127.0      Moderate  
46231    NaN  0.38  11.57   9.76   2.20   15.42   1.82   94.0  Satisfactory  
...      ...   ...    ...    ...    ...     ...    ...    ...           ...  
670810  7.90  0.23   7.95  23.35   0.00    0.00   0.00   55.0  Satisfactory  
670811  5.92  0.35   3.60  14.62   0.00    0.00   0.00   54.0  Satisfactory  
670819  4.65  0.34   4.38  50.73   0.00    0.00   0.00   51.0  Satisfactory  
670821  8.08  0.45   7.12  39.23   0.00    0.00   0.00   51.0  Satisfactory  
670828  3.80  0.49   0.75  15.82    NaN     NaN    NaN   50.0          Good  

[125096 rows x 16 columns]

In [27]:
idx3 = (df['col5']>=1 ) |(df['col9']<=0.5)
df[idx3]

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670824  Visakhapatnam  2020-06-30 19:00   8.25  33.25  0.35  24.05  13.05   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670824  5.55  0.44    1.85   41.38    NaN    NaN    NaN   51.0  Satisfactory  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  

[589463 rows x 16 columns]

In [28]:
df.dtypes

col1      object
col2      object
col3     float64
col4     float64
col5     float64
col6     float64
col7     float64
col8     float64
col9     float64
col10    float64
col11    float64
col12    float64
col13    float64
col14    float64
col15    float64
col16     object
dtype: object

In [29]:
# 변수 형태가 object (문자열 포함)인 열만 선택하기
idx4 = df.dtypes=='object'
print(idx4)
print(type(idx4))
print(idx4.array)
print(type(idx4.array))

col1      True
col2      True
col3     False
col4     False
col5     False
col6     False
col7     False
col8     False
col9     False
col10    False
col11    False
col12    False
col13    False
col14    False
col15    False
col16     True
dtype: bool
<class 'pandas.core.series.Series'>
<PandasArray>
[ True,  True, False, False, False, False, False, False, False, False, False,
 False, False, False, False,  True]
Length: 16, dtype: bool
<class 'pandas.core.arrays.numpy_.PandasArray'>


In [30]:
df.iloc[:,idx4.array]

col1              col2         col16
0           Ahmedabad   2015-01-01 1:00           NaN
1           Ahmedabad   2015-01-01 2:00           NaN
2           Ahmedabad   2015-01-01 3:00           NaN
3           Ahmedabad   2015-01-01 4:00           NaN
4           Ahmedabad   2015-01-01 5:00           NaN
...               ...               ...           ...
670825  Visakhapatnam  2020-06-30 20:00  Satisfactory
670826  Visakhapatnam  2020-06-30 21:00  Satisfactory
670827  Visakhapatnam  2020-06-30 22:00          Good
670828  Visakhapatnam  2020-06-30 23:00          Good
670829  Visakhapatnam   2020-07-01 0:00          Good

[670830 rows x 3 columns]

In [31]:
df.describe()

col3           col4           col5           col6  \
count  530858.000000  380931.000000  558625.000000  557935.000000   
mean       70.067364     124.037024      17.813423      29.589279   
std        76.084568     105.663468      32.702488      29.593462   
min         0.010000       0.010000       0.010000       0.010000   
25%        27.750000      56.610000       3.900000      11.110000   
50%        48.500000      94.890000       8.080000      21.000000   
75%        82.250000     153.100000      16.450000      37.220000   
max       999.990000    1000.000000     499.990000     499.510000   

                col7           col8           col9          col10  \
count  551494.000000  407200.000000  586398.000000  543891.000000   
mean       32.957969      24.268378       2.265773      14.312244   
std        40.536889      29.545867      11.286639      19.788800   
min         0.000000       0.010000       0.000000       0.010000   
25%        10.720000       8.310000       0.420000       4.800000   
50%        21.240000      15.900000       0.810000       8.400000   
75%        37.930000      29.930000       1.380000      15.100000   
max       498.610000     499.970000     498.570000     199.960000   

               col11          col12          col13          col14  \
count  547372.000000  515584.000000  460298.000000  243501.000000   
mean       34.807954       3.127310       8.923422       3.146776   
std        29.930581      16.525254      21.948098       7.944772   
min         0.010000       0.000000       0.000000       0.000000   
25%        13.280000       0.080000       0.470000       0.090000   
50%        26.180000       0.920000       2.770000       0.780000   
75%        47.680000       2.830000       8.750000       3.120000   
max       497.620000     498.070000     499.400000     499.990000   

               col15  
count  545725.000000  
mean      171.587336  
std       165.261902  
min         9.000000  
25%        81.000000  
50%       120.000000  
75%       217.000000  
max      3133.000000

#### 실습
* 열 조건: 형태가 숫자형

* 행 조건: 3열의 값이 평균 이상

> 예: 'col3'>= df['col3'].mean()

* 두 조건을 만족하는 데이터만 filter하기

In [32]:
idx_col = df.dtypes == 'float64'
idx_row = df['col3'] >= df['col3'].mean()

In [33]:
print(df.iloc[idx_row.array,idx_col.array])

          col3    col4   col5   col6    col7   col8   col9  col10  col11  \
668      81.30     NaN  23.23  47.66   75.67    NaN  23.23  50.19  30.83   
669     105.53     NaN  43.73  45.93   94.58    NaN  43.73  31.99  53.83   
670     118.33     NaN  39.17  43.69   87.27    NaN  39.17  44.06  42.88   
671     119.40     NaN  61.20  42.79  107.30    NaN  61.20  20.02  12.62   
672     137.43     NaN  11.02  41.19   52.90    NaN  11.02  38.24  28.25   
...        ...     ...    ...    ...     ...    ...    ...    ...    ...   
670382   71.00  143.00  26.22  60.15   53.30   9.25   1.11   1.40  18.48   
670629   83.75  181.75   0.90  36.45   19.75  19.65   0.93  25.62  68.60   
670677  126.50  185.50   2.77  33.22   19.93  26.65   1.52  17.98  28.48   
670678  169.50  235.75   2.23  30.95   18.30  24.15   1.29  14.80  28.57   
670679  107.75  161.50   1.82  21.62   12.53  16.45   0.54    NaN  28.80   

        col12  col13  col14  col15  
668      0.27   0.00   5.82    NaN  
669      0.00

In [34]:
# 두 pandas dataframe 합치기

df1 = df.loc[:,('col2','col4')]
df2 = df.loc[:,('col1','col3')]

In [35]:
?pd.concat

In [36]:
df3 = pd.concat([df1,df2],axis=1)

In [37]:
df3

col2   col4           col1   col3
0        2015-01-01 1:00    NaN      Ahmedabad    NaN
1        2015-01-01 2:00    NaN      Ahmedabad    NaN
2        2015-01-01 3:00    NaN      Ahmedabad    NaN
3        2015-01-01 4:00    NaN      Ahmedabad    NaN
4        2015-01-01 5:00    NaN      Ahmedabad    NaN
...                  ...    ...            ...    ...
670825  2020-06-30 20:00  36.00  Visakhapatnam   9.50
670826  2020-06-30 21:00  49.25  Visakhapatnam  17.25
670827  2020-06-30 22:00  71.00  Visakhapatnam  36.00
670828  2020-06-30 23:00  63.00  Visakhapatnam  15.75
670829   2020-07-01 0:00  66.00  Visakhapatnam  15.00

[670830 rows x 4 columns]

### 2.4 결측치 처리 하기

In [38]:
df.head()

col1             col2  col3  col4  col5   col6   col7  col8  col9  \
0  Ahmedabad  2015-01-01 1:00   NaN   NaN  1.00  40.01  36.37   NaN  1.00   
1  Ahmedabad  2015-01-01 2:00   NaN   NaN  0.02  27.75  19.73   NaN  0.02   
2  Ahmedabad  2015-01-01 3:00   NaN   NaN  0.08  19.32  11.08   NaN  0.08   
3  Ahmedabad  2015-01-01 4:00   NaN   NaN  0.30  16.45   9.20   NaN  0.30   
4  Ahmedabad  2015-01-01 5:00   NaN   NaN  0.12  14.90   7.85   NaN  0.12   

    col10   col11  col12  col13  col14  col15 col16  
0  122.07     NaN    0.0    0.0    0.0    NaN   NaN  
1   85.90     NaN    0.0    0.0    0.0    NaN   NaN  
2   52.83     NaN    0.0    0.0    0.0    NaN   NaN  
3   39.53  153.58    0.0    0.0    0.0    NaN   NaN  
4   32.63     NaN    0.0    0.0    0.0    NaN   NaN

In [39]:
# nan이면 true 아니면 false
df.isnull()

col1   col2   col3   col4   col5   col6   col7   col8   col9  col10  \
0       False  False   True   True  False  False  False   True  False  False   
1       False  False   True   True  False  False  False   True  False  False   
2       False  False   True   True  False  False  False   True  False  False   
3       False  False   True   True  False  False  False   True  False  False   
4       False  False   True   True  False  False  False   True  False  False   
...       ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
670825  False  False  False  False  False  False  False  False  False   True   
670826  False  False  False  False  False  False  False  False  False  False   
670827  False  False  False  False  False  False  False  False  False  False   
670828  False  False  False  False  False  False  False  False  False  False   
670829  False  False  False  False  False  False  False  False  False  False   

        col11  col12  col13  col14  col15  col16  
0        True  False  False  False   True   True  
1        True  False  False  False   True   True  
2        True  False  False  False   True   True  
3       False  False  False  False   True   True  
4        True  False  False  False   True   True  
...       ...    ...    ...    ...    ...    ...  
670825  False   True   True   True  False  False  
670826  False   True   True   True  False  False  
670827  False   True   True   True  False  False  
670828  False   True   True   True  False  False  
670829  False   True   True   True  False  False  

[670830 rows x 16 columns]

In [40]:
# 각 행별 결측치 갯수
df.isnull().sum(1) 

0         6
1         6
2         6
3         5
4         6
         ..
670825    4
670826    3
670827    3
670828    3
670829    3
Length: 670830, dtype: int64

In [41]:
#각 열별 결측치 갯수
df.isnull().sum()

col1          0
col2          0
col3     139972
col4     289899
col5     112205
col6     112895
col7     119336
col8     263630
col9      84432
col10    126939
col11    123458
col12    155246
col13    210532
col14    427329
col15    125105
col16    125105
dtype: int64

In [42]:
idx5 = df.isnull().sum()<=200000
df.iloc[:,idx5.array]

col1              col2   col3  col5   col6   col7  col9  \
0           Ahmedabad   2015-01-01 1:00    NaN  1.00  40.01  36.37  1.00   
1           Ahmedabad   2015-01-01 2:00    NaN  0.02  27.75  19.73  0.02   
2           Ahmedabad   2015-01-01 3:00    NaN  0.08  19.32  11.08  0.08   
3           Ahmedabad   2015-01-01 4:00    NaN  0.30  16.45   9.20  0.30   
4           Ahmedabad   2015-01-01 5:00    NaN  0.12  14.90   7.85  0.12   
...               ...               ...    ...   ...    ...    ...   ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  2.75  25.57  15.85  0.62   
670826  Visakhapatnam  2020-06-30 21:00  17.25  3.62  33.20  20.62  0.76   
670827  Visakhapatnam  2020-06-30 22:00  36.00  2.20  30.80  18.20  0.58   
670828  Visakhapatnam  2020-06-30 23:00  15.75  1.02  28.90  16.00  0.49   
670829  Visakhapatnam   2020-07-01 0:00  15.00  0.40  26.85  14.05  0.59   

         col10   col11  col12  col15         col16  
0       122.07     NaN    0.0    NaN           NaN  
1        85.90     NaN    0.0    NaN           NaN  
2        52.83     NaN    0.0    NaN           NaN  
3        39.53  153.58    0.0    NaN           NaN  
4        32.63     NaN    0.0    NaN           NaN  
...        ...     ...    ...    ...           ...  
670825     NaN   27.75    NaN   51.0  Satisfactory  
670826    2.02   25.58    NaN   51.0  Satisfactory  
670827    1.77   26.15    NaN   50.0          Good  
670828    0.75   15.82    NaN   50.0          Good  
670829    2.10   17.05    NaN   50.0          Good  

[670830 rows x 12 columns]

In [43]:
# 결측치를 모두 0으로 채우기
df.fillna(0)

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00   0.00   0.00  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00   0.00   0.00  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00   0.00   0.00  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00   0.00   0.00  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00   0.00   0.00  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0       0.00  1.00  122.07    0.00    0.0    0.0    0.0    0.0             0  
1       0.00  0.02   85.90    0.00    0.0    0.0    0.0    0.0             0  
2       0.00  0.08   52.83    0.00    0.0    0.0    0.0    0.0             0  
3       0.00  0.30   39.53  153.58    0.0    0.0    0.0    0.0             0  
4       0.00  0.12   32.63    0.00    0.0    0.0    0.0    0.0             0  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62    0.00   27.75    0.0    0.0    0.0   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    0.0    0.0    0.0   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    0.0    0.0    0.0   50.0          Good  
670828  3.80  0.49    0.75   15.82    0.0    0.0    0.0   50.0          Good  
670829  5.20  0.59    2.10   17.05    0.0    0.0    0.0   50.0          Good  

[670830 rows x 16 columns]

In [44]:
df.fillna(1)

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00   1.00   1.00  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00   1.00   1.00  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00   1.00   1.00  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00   1.00   1.00  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00   1.00   1.00  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0       1.00  1.00  122.07    1.00    0.0    0.0    0.0    1.0             1  
1       1.00  0.02   85.90    1.00    0.0    0.0    0.0    1.0             1  
2       1.00  0.08   52.83    1.00    0.0    0.0    0.0    1.0             1  
3       1.00  0.30   39.53  153.58    0.0    0.0    0.0    1.0             1  
4       1.00  0.12   32.63    1.00    0.0    0.0    0.0    1.0             1  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62    1.00   27.75    1.0    1.0    1.0   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    1.0    1.0    1.0   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    1.0    1.0    1.0   50.0          Good  
670828  3.80  0.49    0.75   15.82    1.0    1.0    1.0   50.0          Good  
670829  5.20  0.59    2.10   17.05    1.0    1.0    1.0   50.0          Good  

[670830 rows x 16 columns]

In [45]:
?df.fillna

In [46]:
values = {'col3': 0, 'col4': 1}
df.fillna(value=values)

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00   0.00   1.00  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00   0.00   1.00  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00   0.00   1.00  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00   0.00   1.00  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00   0.00   1.00  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [47]:
# 연속형 변수를 평균으로 채우기
idx_contin = df.dtypes=='float64'
df_contin=df.loc[:,idx_contin]
print(df_contin)
df_contin_fill = df_contin.fillna(df_contin.mean())
print(df_contin_fill)

         col3   col4  col5   col6   col7  col8  col9   col10   col11  col12  \
0         NaN    NaN  1.00  40.01  36.37   NaN  1.00  122.07     NaN    0.0   
1         NaN    NaN  0.02  27.75  19.73   NaN  0.02   85.90     NaN    0.0   
2         NaN    NaN  0.08  19.32  11.08   NaN  0.08   52.83     NaN    0.0   
3         NaN    NaN  0.30  16.45   9.20   NaN  0.30   39.53  153.58    0.0   
4         NaN    NaN  0.12  14.90   7.85   NaN  0.12   32.63     NaN    0.0   
...       ...    ...   ...    ...    ...   ...   ...     ...     ...    ...   
670825   9.50  36.00  2.75  25.57  15.85  4.57  0.62     NaN   27.75    NaN   
670826  17.25  49.25  3.62  33.20  20.62  3.78  0.76    2.02   25.58    NaN   
670827  36.00  71.00  2.20  30.80  18.20  3.67  0.58    1.77   26.15    NaN   
670828  15.75  63.00  1.02  28.90  16.00  3.80  0.49    0.75   15.82    NaN   
670829  15.00  66.00  0.40  26.85  14.05  5.20  0.59    2.10   17.05    NaN   

        col13  col14  col15  
0         0.0    0.0 

In [48]:
idx_contin = df.dtypes == 'float64'
df_contin = df.loc[:,idx_contin.array]
df_contin_fill = df_contin.fillna(df_contin.mean())
df_contin_fill

col3        col4  col5   col6   col7       col8  col9  \
0       70.067364  124.037024  1.00  40.01  36.37  24.268378  1.00   
1       70.067364  124.037024  0.02  27.75  19.73  24.268378  0.02   
2       70.067364  124.037024  0.08  19.32  11.08  24.268378  0.08   
3       70.067364  124.037024  0.30  16.45   9.20  24.268378  0.30   
4       70.067364  124.037024  0.12  14.90   7.85  24.268378  0.12   
...           ...         ...   ...    ...    ...        ...   ...   
670825   9.500000   36.000000  2.75  25.57  15.85   4.570000  0.62   
670826  17.250000   49.250000  3.62  33.20  20.62   3.780000  0.76   
670827  36.000000   71.000000  2.20  30.80  18.20   3.670000  0.58   
670828  15.750000   63.000000  1.02  28.90  16.00   3.800000  0.49   
670829  15.000000   66.000000  0.40  26.85  14.05   5.200000  0.59   

             col10       col11    col12     col13     col14       col15  
0       122.070000   34.807954  0.00000  0.000000  0.000000  171.587336  
1        85.900000   34.807954  0.00000  0.000000  0.000000  171.587336  
2        52.830000   34.807954  0.00000  0.000000  0.000000  171.587336  
3        39.530000  153.580000  0.00000  0.000000  0.000000  171.587336  
4        32.630000   34.807954  0.00000  0.000000  0.000000  171.587336  
...            ...         ...      ...       ...       ...         ...  
670825   14.312244   27.750000  3.12731  8.923422  3.146776   51.000000  
670826    2.020000   25.580000  3.12731  8.923422  3.146776   51.000000  
670827    1.770000   26.150000  3.12731  8.923422  3.146776   50.000000  
670828    0.750000   15.820000  3.12731  8.923422  3.146776   50.000000  
670829    2.100000   17.050000  3.12731  8.923422  3.146776   50.000000  

[670830 rows x 13 columns]

In [49]:
idx_cat = df.dtypes == 'object'
df_cat = df.loc[:,idx_cat]
df_cat

col1              col2         col16
0           Ahmedabad   2015-01-01 1:00           NaN
1           Ahmedabad   2015-01-01 2:00           NaN
2           Ahmedabad   2015-01-01 3:00           NaN
3           Ahmedabad   2015-01-01 4:00           NaN
4           Ahmedabad   2015-01-01 5:00           NaN
...               ...               ...           ...
670825  Visakhapatnam  2020-06-30 20:00  Satisfactory
670826  Visakhapatnam  2020-06-30 21:00  Satisfactory
670827  Visakhapatnam  2020-06-30 22:00          Good
670828  Visakhapatnam  2020-06-30 23:00          Good
670829  Visakhapatnam   2020-07-01 0:00          Good

[670830 rows x 3 columns]

In [50]:
df_cat['col1'].value_counts()

Delhi                 48192
Ahmedabad             46728
Mumbai                46728
Lucknow               46728
Chennai               46728
Bengaluru             46728
Hyderabad             46643
Patna                 44554
Gurugram              38794
Visakhapatnam         35053
Amritsar              27805
Jorapokhar            26561
Jaipur                25241
Thiruvananthapuram    25187
Amaravati             22784
Brajrajnagar          21004
Talcher               20697
Kolkata               18039
Guwahati              12002
Chandigarh             7263
Shillong               5938
Bhopal                 5439
Kochi                  2390
Ernakulam              2388
Aizawl                 1216
Name: col1, dtype: int64

In [51]:
?pd.DataFrame.mode

In [52]:
cat_modes = df_cat.mode(dropna=False).iloc[0,:]
cat_modes

col1                Delhi
col2     2020-03-11 10:00
col16            Moderate
Name: 0, dtype: object

In [53]:
df_cat_fill = df_cat.fillna(cat_modes)
df_cat_fill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 670830 entries, 0 to 670829
Data columns (total 3 columns):
 #   Column  Non-Null Count   Dtype 
---  ------  --------------   ----- 
 0   col1    670830 non-null  object
 1   col2    670830 non-null  object
 2   col16   670830 non-null  object
dtypes: object(3)
memory usage: 15.4+ MB


In [54]:
df2 = pd.read_excel('./Dataset/dataset_product.xlsx')

In [55]:
df

col1              col2   col3   col4  col5   col6   col7  \
0           Ahmedabad   2015-01-01 1:00    NaN    NaN  1.00  40.01  36.37   
1           Ahmedabad   2015-01-01 2:00    NaN    NaN  0.02  27.75  19.73   
2           Ahmedabad   2015-01-01 3:00    NaN    NaN  0.08  19.32  11.08   
3           Ahmedabad   2015-01-01 4:00    NaN    NaN  0.30  16.45   9.20   
4           Ahmedabad   2015-01-01 5:00    NaN    NaN  0.12  14.90   7.85   
...               ...               ...    ...    ...   ...    ...    ...   
670825  Visakhapatnam  2020-06-30 20:00   9.50  36.00  2.75  25.57  15.85   
670826  Visakhapatnam  2020-06-30 21:00  17.25  49.25  3.62  33.20  20.62   
670827  Visakhapatnam  2020-06-30 22:00  36.00  71.00  2.20  30.80  18.20   
670828  Visakhapatnam  2020-06-30 23:00  15.75  63.00  1.02  28.90  16.00   
670829  Visakhapatnam   2020-07-01 0:00  15.00  66.00  0.40  26.85  14.05   

        col8  col9   col10   col11  col12  col13  col14  col15         col16  
0        NaN  1.00  122.07     NaN    0.0    0.0    0.0    NaN           NaN  
1        NaN  0.02   85.90     NaN    0.0    0.0    0.0    NaN           NaN  
2        NaN  0.08   52.83     NaN    0.0    0.0    0.0    NaN           NaN  
3        NaN  0.30   39.53  153.58    0.0    0.0    0.0    NaN           NaN  
4        NaN  0.12   32.63     NaN    0.0    0.0    0.0    NaN           NaN  
...      ...   ...     ...     ...    ...    ...    ...    ...           ...  
670825  4.57  0.62     NaN   27.75    NaN    NaN    NaN   51.0  Satisfactory  
670826  3.78  0.76    2.02   25.58    NaN    NaN    NaN   51.0  Satisfactory  
670827  3.67  0.58    1.77   26.15    NaN    NaN    NaN   50.0          Good  
670828  3.80  0.49    0.75   15.82    NaN    NaN    NaN   50.0          Good  
670829  5.20  0.59    2.10   17.05    NaN    NaN    NaN   50.0          Good  

[670830 rows x 16 columns]

In [56]:
# np

df_np = df.to_numpy()
df_np

array([['Ahmedabad', '2015-01-01 1:00', nan, ..., 0.0, nan, nan],
       ['Ahmedabad', '2015-01-01 2:00', nan, ..., 0.0, nan, nan],
       ['Ahmedabad', '2015-01-01 3:00', nan, ..., 0.0, nan, nan],
       ...,
       ['Visakhapatnam', '2020-06-30 22:00', 36.0, ..., nan, 50.0,
        'Good'],
       ['Visakhapatnam', '2020-06-30 23:00', 15.75, ..., nan, 50.0,
        'Good'],
       ['Visakhapatnam', '2020-07-01 0:00', 15.0, ..., nan, 50.0, 'Good']],
      dtype=object)

In [57]:
df_np2 = df.values
df_np2

array([['Ahmedabad', '2015-01-01 1:00', nan, ..., 0.0, nan, nan],
       ['Ahmedabad', '2015-01-01 2:00', nan, ..., 0.0, nan, nan],
       ['Ahmedabad', '2015-01-01 3:00', nan, ..., 0.0, nan, nan],
       ...,
       ['Visakhapatnam', '2020-06-30 22:00', 36.0, ..., nan, 50.0,
        'Good'],
       ['Visakhapatnam', '2020-06-30 23:00', 15.75, ..., nan, 50.0,
        'Good'],
       ['Visakhapatnam', '2020-07-01 0:00', 15.0, ..., nan, 50.0, 'Good']],
      dtype=object)

In [58]:
type(df), type(df_np)

(pandas.core.frame.DataFrame, numpy.ndarray)

In [59]:
df_np.shape

(670830, 16)

In [60]:
df_np.dtype, df.dtypes

(dtype('O'),
 col1      object
 col2      object
 col3     float64
 col4     float64
 col5     float64
 col6     float64
 col7     float64
 col8     float64
 col9     float64
 col10    float64
 col11    float64
 col12    float64
 col13    float64
 col14    float64
 col15    float64
 col16     object
 dtype: object)

In [61]:
df_contin_np = df_contin.to_numpy()
df_contin_np

array([[      nan,       nan, 1.000e+00, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 2.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 8.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       ...,
       [3.600e+01, 7.100e+01, 2.200e+00, ...,       nan,       nan,
        5.000e+01],
       [1.575e+01, 6.300e+01, 1.020e+00, ...,       nan,       nan,
        5.000e+01],
       [1.500e+01, 6.600e+01, 4.000e-01, ...,       nan,       nan,
        5.000e+01]])

In [62]:
df_contin_np.shape, df_contin_np.dtype

((670830, 13), dtype('float64'))

In [63]:
df_contin_np[0, 2]

1.0

In [64]:
df_contin_np[0, :]

array([   nan,    nan,   1.  ,  40.01,  36.37,    nan,   1.  , 122.07,
          nan,   0.  ,   0.  ,   0.  ,    nan])

In [65]:
df_cat_np = df_cat.to_numpy()
df_cat_np.dtype

dtype('O')

In [66]:
idx7 = df_contin_np[:,1]>=2
idx7

<ipython-input-66-38872c4cffb4>:1: RuntimeWarning: invalid value encountered in greater_equal
  idx7 = df_contin_np[:,1]>=2


array([False, False, False, ...,  True,  True,  True])

In [74]:
df_contin_np.mean(1)

array([nan, nan, nan, ..., nan, nan, nan])

In [73]:
np.nanmean(df_contin_np), np.nanmean(df_contin_np, 0)

(41.56496389319007,
 array([ 70.06736366, 124.03702445,  17.81342348,  29.58927888,
         32.95796941,  24.2683775 ,   2.26577333,  14.31224418,
         34.8079538 ,   3.12731016,   8.92342244,   3.14677558,
        171.58733611]))

In [75]:
df_np1 = df_contin_np[:3, :5]
df_np2 = df_contin_np[3:6, :5]

In [76]:
df_np1, df_np2

(array([[      nan,       nan, 1.000e+00, 4.001e+01, 3.637e+01],
        [      nan,       nan, 2.000e-02, 2.775e+01, 1.973e+01],
        [      nan,       nan, 8.000e-02, 1.932e+01, 1.108e+01]]),
 array([[  nan,   nan,  0.3 , 16.45,  9.2 ],
        [  nan,   nan,  0.12, 14.9 ,  7.85],
        [  nan,   nan,  0.33, 15.95, 10.82]]))

In [78]:
df_np3 = np.concatenate((df_np1,df_np2))
df_np3

array([[      nan,       nan, 1.000e+00, 4.001e+01, 3.637e+01],
       [      nan,       nan, 2.000e-02, 2.775e+01, 1.973e+01],
       [      nan,       nan, 8.000e-02, 1.932e+01, 1.108e+01],
       [      nan,       nan, 3.000e-01, 1.645e+01, 9.200e+00],
       [      nan,       nan, 1.200e-01, 1.490e+01, 7.850e+00],
       [      nan,       nan, 3.300e-01, 1.595e+01, 1.082e+01]])

In [79]:
df_np4 = np.concatenate((df_np1, df_np2), axis = 1)
df_np4

array([[      nan,       nan, 1.000e+00, 4.001e+01, 3.637e+01,       nan,
              nan, 3.000e-01, 1.645e+01, 9.200e+00],
       [      nan,       nan, 2.000e-02, 2.775e+01, 1.973e+01,       nan,
              nan, 1.200e-01, 1.490e+01, 7.850e+00],
       [      nan,       nan, 8.000e-02, 1.932e+01, 1.108e+01,       nan,
              nan, 3.300e-01, 1.595e+01, 1.082e+01]])

In [80]:
idx_missing = np.isnan(df_contin_np)
idx_missing

array([[ True,  True, False, ..., False, False,  True],
       [ True,  True, False, ..., False, False,  True],
       [ True,  True, False, ..., False, False,  True],
       ...,
       [False, False, False, ...,  True,  True, False],
       [False, False, False, ...,  True,  True, False],
       [False, False, False, ...,  True,  True, False]])

In [84]:
np.isnan(df_contin_np).sum(0)

array([139972, 289899, 112205, 112895, 119336, 263630,  84432, 126939,
       123458, 155246, 210532, 427329, 125105])

In [85]:
from sklearn.impute import *
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.impute import KNNImputer

In [86]:
?SimpleImputer

In [89]:
imp_mean = SimpleImputer(strategy='mean', missing_values=np.nan)
imp_mean.fit(df_contin_np)

SimpleImputer()

In [90]:
imp_mean.statistics_

array([ 70.06736366, 124.03702445,  17.81342348,  29.58927888,
        32.95796941,  24.2683775 ,   2.26577333,  14.31224418,
        34.8079538 ,   3.12731016,   8.92342244,   3.14677558,
       171.58733611])

In [91]:
imp_mean.transform(df_contin_np)

array([[7.00673637e+01, 1.24037024e+02, 1.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 1.71587336e+02],
       [7.00673637e+01, 1.24037024e+02, 2.00000000e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.71587336e+02],
       [7.00673637e+01, 1.24037024e+02, 8.00000000e-02, ...,
        0.00000000e+00, 0.00000000e+00, 1.71587336e+02],
       ...,
       [3.60000000e+01, 7.10000000e+01, 2.20000000e+00, ...,
        8.92342244e+00, 3.14677558e+00, 5.00000000e+01],
       [1.57500000e+01, 6.30000000e+01, 1.02000000e+00, ...,
        8.92342244e+00, 3.14677558e+00, 5.00000000e+01],
       [1.50000000e+01, 6.60000000e+01, 4.00000000e-01, ...,
        8.92342244e+00, 3.14677558e+00, 5.00000000e+01]])

In [92]:
df_contin_np

array([[      nan,       nan, 1.000e+00, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 2.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       [      nan,       nan, 8.000e-02, ..., 0.000e+00, 0.000e+00,
              nan],
       ...,
       [3.600e+01, 7.100e+01, 2.200e+00, ...,       nan,       nan,
        5.000e+01],
       [1.575e+01, 6.300e+01, 1.020e+00, ...,       nan,       nan,
        5.000e+01],
       [1.500e+01, 6.600e+01, 4.000e-01, ...,       nan,       nan,
        5.000e+01]])

In [93]:
imp_median = SimpleImputer(strategy='median', missing_values=np.nan)
imp_median.fit_transform(df_contin_np)

array([[4.850e+01, 9.489e+01, 1.000e+00, ..., 0.000e+00, 0.000e+00,
        1.200e+02],
       [4.850e+01, 9.489e+01, 2.000e-02, ..., 0.000e+00, 0.000e+00,
        1.200e+02],
       [4.850e+01, 9.489e+01, 8.000e-02, ..., 0.000e+00, 0.000e+00,
        1.200e+02],
       ...,
       [3.600e+01, 7.100e+01, 2.200e+00, ..., 2.770e+00, 7.800e-01,
        5.000e+01],
       [1.575e+01, 6.300e+01, 1.020e+00, ..., 2.770e+00, 7.800e-01,
        5.000e+01],
       [1.500e+01, 6.600e+01, 4.000e-01, ..., 2.770e+00, 7.800e-01,
        5.000e+01]])

In [94]:
?KNNImputer

In [96]:
df_contin_np2 = df_contin.sample(10000).to_numpy()
df_contin_np2.shape

(10000, 13)

In [97]:
imp_KNN = KNNImputer(n_neighbors=5, missing_values=np.nan)
imp_KNN.fit_transform(df_contin_np2)

array([[3.94740e+01, 3.34340e+01, 7.11200e+00, ..., 0.00000e+00,
        0.00000e+00, 8.26000e+01],
       [4.61600e+01, 5.56100e+01, 4.97000e+00, ..., 2.44000e+00,
        3.47000e+00, 1.01000e+02],
       [5.23740e+01, 8.76360e+01, 8.64200e+00, ..., 1.70000e-01,
        1.40000e-02, 8.52000e+01],
       ...,
       [2.40000e+01, 3.85000e+01, 9.05000e+00, ..., 1.52000e+00,
        3.80000e-01, 3.40000e+01],
       [4.34540e+01, 1.06064e+02, 5.29000e+00, ..., 1.08400e+01,
        1.48000e+00, 9.46000e+01],
       [1.89140e+02, 2.89300e+02, 1.40000e+01, ..., 1.74000e+01,
        1.00000e-02, 3.33000e+02]])

In [98]:
?IterativeImputer

In [100]:
imp_mice = IterativeImputer(missing_values=np.nan)
imp_mice.fit_transform(df_contin_np2)

/home/pirl/anaconda3/lib/python3.8/site-packages/sklearn/impute/_iterative.py:669: ConvergenceWarning: [IterativeImputer] Early stopping criterion not reached.
  warnings.warn("[IterativeImputer] Early stopping criterion not"


array([[8.16981823e+01, 1.52936085e+02, 3.55801370e+01, ...,
        0.00000000e+00, 0.00000000e+00, 1.69829759e+02],
       [4.61600000e+01, 5.56100000e+01, 4.97000000e+00, ...,
        2.44000000e+00, 3.47000000e+00, 1.01000000e+02],
       [6.88514612e+01, 1.36278353e+02, 1.62093637e+01, ...,
        7.84460411e+00, 2.01170142e+00, 1.48273157e+02],
       ...,
       [2.40000000e+01, 3.85000000e+01, 9.05000000e+00, ...,
        1.52000000e+00, 3.80000000e-01, 3.40000000e+01],
       [6.13440797e+01, 1.20511703e+02, 5.29000000e+00, ...,
        1.08400000e+01, 1.48000000e+00, 1.39840843e+02],
       [1.89140000e+02, 2.89300000e+02, 1.40000000e+01, ...,
        1.74000000e+01, 1.00000000e-02, 3.33000000e+02]])